### ISSUE TITLE
Object reference not set to an instance of an object when opening an existing snippet

### ISSUE THREAD

**Issue by MikeYeager** [AlessandroDelSole/CodeSnippetStudio#15] opened 2016-09-07 14:54 UTC
I installed the tool in VS2015 on my new computer and tried to edit a custom snippet I have installed from a previous edition. When I select the snippet file to open, I get this exception. I selected C# as the language, but did nothing else. The other odd thing is that it always says, "The current snippet has unsaved changes. Are you sure?" when I try to open an existing snippet. But the editor window is blank. The current snippet is just the blank window that comes up when I start the program. Any ideas?

**Comment by AlessandroDelSole** [comment] 2016-09-07 15:11
Hi Mike,
thanks for reporting this. Can you please confirm you have version 1.3.6 installed? This should solve that problem.

About the second issue, it is actually a known issue. The reason is that the data-bound object that represents a snippet raises property change notifications for author, title, etc. and this affects the check of pending changes even if the editor is blank. This is something that must be definitely fixed.

Best.

**Comment by MikeYeager** [comment] 2016-09-07 15:49
Yes,

I just installed from the VS Gallery and it is 1.3.6.

Mike

**Comment by MikeYeager** [comment] 2016-09-07 17:14
Here is some more information. The first couple of snippets I tried gave me this exception. When I later went back and tried other snippets, they worked! So it’s not all snippets as I thought. Attached is a snippet file (for C#) that throws the exception.

Mike

**Comment by MikeYeager** [comment] 2016-09-07 21:28
I can see replying with an attachment doesn't work very well. I also can't seem to attach it her in GitHub. Here is the content of one of the snippets that doesn't work:

<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <SnippetTypes>
        <SnippetType>Expansion</SnippetType>
      </SnippetTypes>
      <Title>AsyncWorker</Title>
      <Author>myeager@eps-software.com</Author>
      <Description>
      </Description>
      <HelpUrl>
      </HelpUrl>
      <Shortcut>aw</Shortcut>
    </Header>
    <Snippet>
      <Declarations>
        <Literal Editable="true">
          <ID>CallName</ID>
          <ToolTip>
          </ToolTip>
          <Default>CallName</Default>
          <Function>
          </Function>
        </Literal>
        <Literal Editable="true">
          <ID>Collection</ID>
          <ToolTip>
          </ToolTip>
          <Default>Collection</Default>
          <Function>
          </Function>
        </Literal>
        <Literal Editable="true">
          <ID>Item</ID>
          <ToolTip>
          </ToolTip>
          <Default>Item</Default>
          <Function>
          </Function>
        </Literal>
      </Declarations>
      <Code Language="csharp" Delimiter="$"><![CDATA[            AsyncWorker.Execute(() =>
            {
                $CallName$Response response = null;
                var request = new $CallName$Request {  };
                ServiceClient.Call<ImSpaService>(service => response = service.$CallName$(request));
                return response;
            },
            response =>
            {
                if (response == null)
                {
                    Controller.Message("There was a communications error", icon: MessageBoxImages.Error);
                    return;
                }
                else if (response.Success)
                {
                    //$Collection$s.Clear();
                    //foreach (var item in response.$Collection$s)
                    //{
                    //    var newItem = new $Collection$ListItemViewModel();
                    //    Mapper.Map(item, newItem);
                    //    $Collection$s.Add(newitem);
                    //}

```
                //Mapper.Map(response.$Item$, this);
            }
            else
            {
                Controller.Message(response.FailureInformation, icon: MessageBoxImages.Error);
            }
        }, this);]]></Code>
</Snippet>
```

  </CodeSnippet>
</CodeSnippets>

**Comment by MikeYeager** [comment] 2016-09-07 21:29
Let's try that again...

`<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <SnippetTypes>
        <SnippetType>Expansion</SnippetType>
      </SnippetTypes>
      <Title>AsyncWorker</Title>
      <Author>myeager@eps-software.com</Author>
      <Description>
      </Description>
      <HelpUrl>
      </HelpUrl>
      <Shortcut>aw</Shortcut>
    </Header>
    <Snippet>
      <Declarations>
        <Literal Editable="true">
          <ID>CallName</ID>
          <ToolTip>
          </ToolTip>
          <Default>CallName</Default>
          <Function>
          </Function>
        </Literal>
        <Literal Editable="true">
          <ID>Collection</ID>
          <ToolTip>
          </ToolTip>
          <Default>Collection</Default>
          <Function>
          </Function>
        </Literal>
        <Literal Editable="true">
          <ID>Item</ID>
          <ToolTip>
          </ToolTip>
          <Default>Item</Default>
          <Function>
          </Function>
        </Literal>
      </Declarations>
      <Code Language="csharp" Delimiter="$"><![CDATA[            AsyncWorker.Execute(() =>
            {
                $CallName$Response response = null;
                var request = new $CallName$Request {  };
                ServiceClient.Call<ImSpaService>(service => response = service.$CallName$(request));
                return response;
            },
            response =>
            {
                if (response == null)
                {
                    Controller.Message("There was a communications error", icon: MessageBoxImages.Error);
                    return;
                }
                else if (response.Success)
                {
                    //$Collection$s.Clear();
                    //foreach (var item in response.$Collection$s)
                    //{
                    //    var newItem = new $Collection$ListItemViewModel();
                    //    Mapper.Map(item, newItem);
                    //    $Collection$s.Add(newitem);
                    //}

```
                //Mapper.Map(response.$Item$, this);
            }
            else
            {
                Controller.Message(response.FailureInformation, icon: MessageBoxImages.Error);
            }
        }, this);]]></Code>
</Snippet>
```

  </CodeSnippet>
</CodeSnippets>`

**Comment by MikeYeager** [comment] 2016-09-07 21:30
No, I guess it won't even accept it as "code". It seems if I zip it, I can attach the zip file. Yea! Take that GitHub <s>.

[aw.zip](https://github.com/AlessandroDelSole/CodeSnippetStudio/files/460384/aw.zip)

**Comment by AlessandroDelSole** [comment] 2016-09-09 11:11
I was able to reproduce the issue. Apparently, looks like the snippet is missing some property assignment. Behind the scenes, Studio uses another project of mine, the DelSole.VSIX library (still on GitHub) which is probably the place I'll check-in for the issue.

I'll keep you posted. Thanks.

**Comment by MikeYeager** [comment] 2016-09-09 14:05
Thank you!

**Comment by AlessandroDelSole** [comment] 2016-09-09 21:01
The issue has been resolved, it was a bug in the DelSole.VSIX library that Studio relies on. Please check for version 1.3.7 of the extension for Visual Studio 2015 in less than an hour. I'll be updating a new commit in a few minutes. I'm closing this, but please feel free to reopen the issue if the problem is not solved.

I was able to open the code snippet you sent with no problems. Thanks again.

**Comment by AlessandroDelSole** [comment] 2016-09-09 21:20
I'm reopening the issue myself because it looks like v 1.3.7 is still unstable. I'll keep you posted

**Comment by MikeYeager** [comment] 2016-09-09 21:35
Thank you. Have a great weekend!

**Comment by AlessandroDelSole** [comment] 2016-09-09 21:35
It's fine now. Check the Visual Studio Gallery for 1.3.7 in a few minutes!

**Closed as completed** 2016-09-09 21:34 UTC
Labels: bug, fixed

**Comment by MikeYeager** [comment] 2016-09-09 21:40
Will do!

**Comment by MikeYeager** [comment] 2016-09-14 17:33
Alessandro,

That seems to have done the trick! Thank you very much! Great tool!

Mike Yeager
